cc_library(
    name = "substructures",
    srcs = [
        "EventLinkageInfo.cpp",
        "ExtendedEventLinkageInfo.cpp",
        "MobileHandOverLinkage.cpp",
    ],
    hdrs = [
        "EventLinkageInfo.h",
        "ExtendedEventLinkageInfo.h",
        "MobileHandOverLinkage.h"
    ],
    visibility = [""]

)